services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sportsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"     # наружу 5433, внутри 5432
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: