services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sportsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flask:
    build: ./app
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./data:/shared_data

  airflow:
    image: apache/airflow:2.7.2
    depends_on:
      - db
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@db:5432/sportsdb
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/shared_data
    ports:
      - "8080:8080"
    command: >
      bash -c "
        echo 'Waiting for Postgres...'; 
        while ! pg_isready -h db -p 5432 > /dev/null 2>&1; do sleep 2; done;
        echo 'Postgres is ready. Starting Airflow DB INIT...';
        airflow db init || true &&
        airflow db migrate &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || true &&
        airflow scheduler & airflow webserver
      "

volumes:
  postgres_data:

