data_source postgres_chicago:
  type: postgres
  connection:
    host: ${POSTGRES_HOST=db}
    port: ${POSTGRES_PORT=5432}
    username: ${POSTGRES_USER=user}
    password: ${POSTGRES_PASSWORD=password}
    database: ${POSTGRES_DB=sportsdb}
